name: deeplearning
channels:
- anaconda
- defaults
dependencies:
- hdf5=1.8.17=vc14_0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- pip=9.0.1=py36_1
- python=3.6.1=2
- pywin32=220=py36_2
- setuptools=27.2.0=py36_1
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py36_0
- zlib=1.2.8=vc14_3
- bleach=1.5.0=py36_0
- colorama=0.3.9=py36_0
- cycler=0.10.0=py36_0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- html5lib=0.999=py36_0
- icu=57.1=vc14_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jpeg=9b=vc14_0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.0.1=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libpng=1.6.27=vc14_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.2=np112py36_0
- mistune=0.7.4=py36_0
- nbconvert=5.2.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=5.0.0=py36_0
- openssl=1.0.2l=vc14_0
- pandas=0.20.2=np112py36_0
- pandocfilters=1.4.1=py36_0
- path.py=10.3.1=py36_0
- pickleshare=0.7.4=py36_0
- prompt_toolkit=1.0.14=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=vc14_4
- qtconsole=4.3.0=py36_0
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=vc14_0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- widgetsnbextension=2.0.0=py36_0
- pip:
  - curses==2.2
  - h5py==2.7.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - olefile==0.44
  - opencv-python==3.2.0
  - pillow==4.1.1
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - pyautogui==0.9.36
  - pymsgbox==1.0.6
  - pyscreeze==0.1.9
  - pytweening==1.0.3
  - tensorflow==1.1.0
  - tflearn==0.3.1
  - werkzeug==0.12.2
prefix: C:\Users\Jonny\AppData\Local\conda\conda\envs\deeplearning

